### ISSUE TITLE
When editing video Description and Tags don't update

### ISSUE THREAD

**Issue by mbaran3** [orlb/fossflix#2]
When you edit a video to change the tags or description, then click to another video then click back to the original video, old  description and tags reappear. This only happens if the title remains unchanged.

**Comment by acmattson3** [comment]
In trying to replicate this issue myself, I ran into no problems. Is this still an issue you are having?

I changed the description and tags of a movie, clicked "update movie," clicked a new movie, and clicked back to the changed movie, and I was given the correctly changed description and tags.

Is it possible you neglected to press the "update movie" button? In that case, this is the expected behavior.

**Comment by mbaran3** [comment]
I can not repeat the issue it was either a bug with something on my end, or I am retarded we might never know
